const RELIGION_IMAGE_FILES: Record<string, string> = {
  sumerian: "sumerian.webp",
  egyptian: "egyptian.webp",
  zoroastrian: "Zoroastrianism.webp",
  canaanite: "Canaanite.webp",
  "greek-roman": "Greco-Roman.webp",
  norse: "Norse.webp",
  druidic: "Celtic.webp",
  manichaean: "Manichaeism.webp",
  tengrism: "tengrism.webp",
  mithraism: "Mithraism.webp",
  hinduism: "Hindu.webp",
  buddhism: "Buddhism.webp",
  jainism: "jainism.webp",
  sikhism: "Sikhism.webp",
  judaism: "judaism.webp",
  christianity: "christianity.webp",
  islam: "islam.webp",
  bahai: "bahai.webp",
  taoism: "daoism.webp",
  shinto: "shinto.webp",
  gnosticism: "gnosticism.webp",
  confucianism: "confucianism.webp",
  mesoamerican: "mesoamerican.webp",
  mandaean: "mandaean.webp",
  yoruba: "yoruba.webp",
  bon: "bon.webp",
  stoicism: "stoicism.webp",
  "slavic-baltic": "slavic-baltic.webp",
  samaritan: "samaritan.webp",
  cheondogyo: "cheondogyo.webp",
  "chinese-folk": "chinese-folk.webp",
  caodai: "caodai.webp",
  yazidi: "yazidi.webp",
  druse: "druse.webp",
  santeria: "santeria.webp",
  vodou: "vodou.webp",
  inuit: "inuit.webp",
  navajo: "navajo.webp",
  maori: "maori.webp",
  dreamtime: "dreaming.webp",
  ifa: "ifa.webp",
  candomble: "candomble.webp",
  wicca: "wicca.webp",
  rastafari: "rastafari.webp",
  "korean-shin": "korean-shin.webp",
};

export function getReligionImageSrc(religionId: string): string | undefined {
  const file = RELIGION_IMAGE_FILES[religionId];
  return file ? `/assets/img/${file}` : undefined;
}

const RELIGION_THUMBNAIL_FILES: Record<string, string> = {
  bahai: "bahai-thumb.webp",
  taoism: "daoism-thumb.webp",
  shinto: "shinto-thumb.webp",
  gnosticism: "gnosticism-thumb.webp",
  confucianism: "confucianism-thumb.webp",
  mesoamerican: "mesoamerican-thumb.webp",
  mandaean: "mandaean-thumb.webp",
  yoruba: "yoruba-thumb.webp",
  bon: "bon-thumb.webp",
  stoicism: "stoicism-thumb.webp",
  "slavic-baltic": "slavic-baltic-thumb.webp",
  samaritan: "samaritan-thumb.webp",
  cheondogyo: "cheondogyo-thumb.webp",
  "chinese-folk": "chinese-folk-thumb.webp",
  caodai: "caodai-thumb.webp",
  yazidi: "yazidi-thumb.webp",
  druse: "druse-thumb.webp",
  santeria: "santeria-thumb.webp",
  vodou: "vodou-thumb.webp",
  inuit: "inuit-thumb.webp",
  navajo: "navajo-thumb.webp",
  maori: "maori-thumb.webp",
  dreamtime: "dreaming-thumb.webp",
  ifa: "ifa-thumb.webp",
  candomble: "candomble-thumb.webp",
  wicca: "wicca-thumb.webp",
  rastafari: "rastafari-thumb.webp",
  "korean-shin": "korean-shin-thumb.webp",
};

export function getReligionThumbnailSrc(religionId: string): string | undefined {
  const file = RELIGION_THUMBNAIL_FILES[religionId];
  return file ? `/assets/img/${file}` : undefined;
}
