// AUTO-GENERATED by scripts/scaffold-locale-articles.ts — do not hand-edit.
// Re-run `npx tsx scripts/scaffold-locale-articles.ts fa` after
// adding/removing a tradition to keep this in sync.
import type { ReligionArticle } from "../types";
import { bahaiArticleFa } from "./bahai";
import { bonArticleFa } from "./bon";
import { buddhismArticleFa } from "./buddhism";
import { canaaniteArticleFa } from "./canaanite";
import { candombleArticleFa } from "./candomble";
import { caodaiArticleFa } from "./caodai";
import { chineseFolkArticleFa } from "./chinese-folk";
import { christianityArticleFa } from "./christianity";
import { confucianismArticleFa } from "./confucianism";
import { dreamtimeArticleFa } from "./dreamtime";
import { druidicArticleFa } from "./druidic";
import { druseArticleFa } from "./druse";
import { egyptianArticleFa } from "./egyptian";
import { gnosticismArticleFa } from "./gnosticism";
import { greekRomanArticleFa } from "./greek-roman";
import { hinduismArticleFa } from "./hinduism";
import { ifaArticleFa } from "./ifa";
import { inuitArticleFa } from "./inuit";
import { islamArticleFa } from "./islam";
import { jainismArticleFa } from "./jainism";
import { judaismArticleFa } from "./judaism";
import { koreanShinArticleFa } from "./korean-shin";
import { mandaeanArticleFa } from "./mandaean";
import { manichaeanArticleFa } from "./manichaean";
import { maoriArticleFa } from "./maori";
import { mesoamericanArticleFa } from "./mesoamerican";
import { mithraismArticleFa } from "./mithraism";
import { navajoArticleFa } from "./navajo";
import { norseArticleFa } from "./norse";
import { rastafariArticleFa } from "./rastafari";
import { samaritanArticleFa } from "./samaritan";
import { santeriaArticleFa } from "./santeria";
import { shintoArticleFa } from "./shinto";
import { sikhismArticleFa } from "./sikhism";
import { slavicBalticArticleFa } from "./slavic-baltic";
import { stoicismArticleFa } from "./stoicism";
import { sumerianArticleFa } from "./sumerian";
import { taoismArticleFa } from "./taoism";
import { tengrismArticleFa } from "./tengrism";
import { vodouArticleFa } from "./vodou";
import { wiccaArticleFa } from "./wicca";
import { yazidiArticleFa } from "./yazidi";
import { yorubaArticleFa } from "./yoruba";
import { zoroastrianArticleFa } from "./zoroastrian";

/**
 * Persian (fa) article map. An entry here may still be
 * the English content re-exported as a placeholder (see the TODO
 * comment in each file) — getReligionArticle() in ../index.ts does not
 * distinguish translated from placeholder entries, both render fine,
 * translated ones are just correct.
 */
export const ARTICLES_FA: Record<string, ReligionArticle> = {
  "bahai": bahaiArticleFa,
  "bon": bonArticleFa,
  "buddhism": buddhismArticleFa,
  "canaanite": canaaniteArticleFa,
  "candomble": candombleArticleFa,
  "caodai": caodaiArticleFa,
  "chinese-folk": chineseFolkArticleFa,
  "christianity": christianityArticleFa,
  "confucianism": confucianismArticleFa,
  "dreamtime": dreamtimeArticleFa,
  "druidic": druidicArticleFa,
  "druse": druseArticleFa,
  "egyptian": egyptianArticleFa,
  "gnosticism": gnosticismArticleFa,
  "greek-roman": greekRomanArticleFa,
  "hinduism": hinduismArticleFa,
  "ifa": ifaArticleFa,
  "inuit": inuitArticleFa,
  "islam": islamArticleFa,
  "jainism": jainismArticleFa,
  "judaism": judaismArticleFa,
  "korean-shin": koreanShinArticleFa,
  "mandaean": mandaeanArticleFa,
  "manichaean": manichaeanArticleFa,
  "maori": maoriArticleFa,
  "mesoamerican": mesoamericanArticleFa,
  "mithraism": mithraismArticleFa,
  "navajo": navajoArticleFa,
  "norse": norseArticleFa,
  "rastafari": rastafariArticleFa,
  "samaritan": samaritanArticleFa,
  "santeria": santeriaArticleFa,
  "shinto": shintoArticleFa,
  "sikhism": sikhismArticleFa,
  "slavic-baltic": slavicBalticArticleFa,
  "stoicism": stoicismArticleFa,
  "sumerian": sumerianArticleFa,
  "taoism": taoismArticleFa,
  "tengrism": tengrismArticleFa,
  "vodou": vodouArticleFa,
  "wicca": wiccaArticleFa,
  "yazidi": yazidiArticleFa,
  "yoruba": yorubaArticleFa,
  "zoroastrian": zoroastrianArticleFa,
};
