/**
 * Generates one translation stub file per tradition under
 * src/data/religion-articles/<locale>/, plus that directory's
 * articles.ts index (mirrors ../articles.ts). Safe to re-run: existing
 * per-tradition files (i.e. anything already translated) are left
 * untouched; only <locale>/articles.ts is always regenerated so it
 * stays in sync with whichever ids have real translations vs still-
 * English placeholders.
 *
 * Usage:
 *   npx tsx scripts/scaffold-locale-articles.ts fa
 *   npx tsx scripts/scaffold-locale-articles.ts ar
 *
 * Locale arg must already exist in LOCALE_REGISTRY (src/lib/locale.ts)
 * — add it there first. See docs/i18n.md for the full workflow.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { ARTICLES } from "../src/data/religion-articles/articles";
import { LOCALE_REGISTRY } from "../src/lib/locale";

const locale = process.argv[2];

if (!locale) {
  console.error("Usage: npx tsx scripts/scaffold-locale-articles.ts <locale-code>");
  console.error(`Registered locales: ${LOCALE_REGISTRY.map((l) => l.code).join(", ")}`);
  process.exit(1);
}

const meta = LOCALE_REGISTRY.find((l) => l.code === locale);
if (!meta) {
  console.error(
    `"${locale}" is not in LOCALE_REGISTRY (src/lib/locale.ts). Add it there first, then re-run this script.`
  );
  process.exit(1);
}

function toCamel(id: string): string {
  return id.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

function toPascal(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const ROOT = resolve(process.cwd(), "src/data/religion-articles");
const LOCALE_DIR = resolve(ROOT, locale);
mkdirSync(LOCALE_DIR, { recursive: true });

const suffix = toPascal(locale); // e.g. "Fa", "Ar" — used in export names below
const ids = Object.keys(ARTICLES).sort();
let created = 0;
let skipped = 0;

for (const id of ids) {
  const exportName = `${toCamel(id)}Article`;
  const localeExportName = `${toCamel(id)}Article${suffix}`;
  const outPath = resolve(LOCALE_DIR, `${id}.ts`);

  if (existsSync(outPath)) {
    skipped++;
    continue;
  }

  const content = `/**
 * TODO(${locale}-translation): translate every string field to ${meta.englishName}.
 *
 * This file currently just re-exports the English article as a
 * placeholder, so /${locale}/religion/${id} renders correctly (in
 * English) instead of breaking while untranslated. To translate this
 * tradition: replace the re-export below with a real object literal of
 * type ReligionArticle, translating every string while preserving the
 * exact key structure (overview, history, worldview, texts, practice,
 * diversity, communities, places, debates, keyTerms, sources).
 *
 * See docs/i18n.md for the full workflow, tone/register and
 * terminology guidance, and a worked example.
 *
 * English source: ../${id}.ts
 */
import type { ReligionArticle } from "../types";
import { ${exportName} } from "../${id}";

export const ${localeExportName}: ReligionArticle = ${exportName};
`;

  writeFileSync(outPath, content, "utf8");
  created++;
}

const indexContent = `// AUTO-GENERATED by scripts/scaffold-locale-articles.ts — do not hand-edit.
// Re-run \`npx tsx scripts/scaffold-locale-articles.ts ${locale}\` after
// adding/removing a tradition to keep this in sync.
import type { ReligionArticle } from "../types";
${ids.map((id) => `import { ${toCamel(id)}Article${suffix} } from "./${id}";`).join("\n")}

/**
 * ${meta.englishName} (${locale}) article map. An entry here may still be
 * the English content re-exported as a placeholder (see the TODO
 * comment in each file) — getReligionArticle() in ../index.ts does not
 * distinguish translated from placeholder entries, both render fine,
 * translated ones are just correct.
 */
export const ARTICLES_${locale.toUpperCase()}: Record<string, ReligionArticle> = {
${ids.map((id) => `  "${id}": ${toCamel(id)}Article${suffix},`).join("\n")}
};
`;

writeFileSync(resolve(LOCALE_DIR, "articles.ts"), indexContent, "utf8");

console.log(
  `Scaffolded ${locale}/ articles: ${created} stub file(s) created, ${skipped} already existed (left untouched). ${locale}/articles.ts regenerated with ${ids.length} entries.`
);
